In [5]:
import duckdb

In [7]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [13]:
df = con.execute("""
                 SELECT * FROM ( 
                    select *, row_number() over(partition by NATBR ORDER BY data_ingestao desc) as row 
                    from bronze_z0019
                    where data_ingestao >= '2025-12-07'
                 ) WHERE row = 1
                 """).fetchdf()
        
df.head()

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao,row
0,10003,PREGO,BT10,100,60,z0019_2.csv,2025-12-07 20:29:06.840296,1
1,10004,SERRA,BT50,100,200,z0019_2.csv,2025-12-07 20:29:06.840296,1
2,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-12-07 20:27:01.971089,1
3,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-12-07 20:27:01.971089,1

In [16]:
df_final = df.drop(columns=['nome_arquivo','data_ingestao','row'])
df_final = df_final.rename(columns={"NATBR":"ID"})
df_final = df_final.rename(columns={"MAKTX":"NM_PRODUTO"})
df_final = df_final.rename(columns={"WERKS":"ID_CATEGORIA"})
df_final = df_final.rename(columns={"NAMAINS":"ID_FORNECEDOR"})
df_final = df_final.rename(columns={"LABST":"VL_PRECO"})
df_final.head(10)

      ID NM_PRODUTO ID_CATEGORIA  MAINS  VL_PRECO
0  10003      PREGO         BT10    100        60
1  10004      SERRA         BT50    100       200
2  10001   PARAFUSO         BT10    100       100
3  10002    MARTELO         BT50    100      1500

In [17]:
con.close()